In [5]:
import numpy as np

X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [3]:
X

array([[0, 0, 4, 0, 4, 0, 2, 0, 2, 2, 2, 3, 1, 2, 0, 0, 1, 3, 4, 4, 0, 0,
        0, 4, 2, 4, 3, 3, 1, 0, 3, 0, 3, 2, 0, 4, 2, 0, 3, 1, 2, 3, 4, 2,
        2, 0, 4, 3, 2, 3, 4, 4, 4, 0, 4, 2, 3, 2, 3, 0, 4, 3, 1, 3, 4, 0,
        3, 4, 0, 4, 4, 2, 4, 0, 1, 0, 1, 4, 4, 2, 1, 1, 3, 3, 4, 3, 0, 0,
        2, 1, 0, 0, 0, 1, 4, 2, 4, 2, 3, 1],
       [3, 4, 3, 3, 3, 1, 3, 4, 3, 2, 4, 0, 1, 3, 0, 3, 3, 0, 1, 2, 3, 4,
        0, 1, 1, 2, 0, 2, 1, 1, 0, 4, 1, 4, 0, 0, 3, 4, 0, 1, 4, 2, 1, 0,
        2, 3, 0, 3, 2, 0, 2, 4, 2, 1, 2, 3, 0, 4, 3, 2, 0, 4, 1, 2, 0, 1,
        2, 1, 4, 3, 2, 1, 4, 0, 4, 3, 4, 2, 3, 3, 0, 0, 0, 1, 2, 0, 1, 0,
        2, 2, 2, 0, 2, 2, 4, 0, 2, 1, 3, 2],
       [2, 2, 1, 3, 3, 3, 2, 4, 4, 3, 0, 0, 4, 1, 3, 2, 3, 1, 4, 1, 3, 1,
        2, 3, 3, 2, 1, 0, 2, 4, 2, 0, 4, 4, 4, 2, 2, 0, 1, 1, 3, 0, 3, 4,
        3, 2, 4, 2, 3, 4, 0, 3, 3, 4, 1, 2, 3, 1, 2, 1, 2, 0, 4, 3, 0, 3,
        0, 3, 1, 0, 3, 2, 4, 0, 1, 2, 2, 1, 3, 3, 3, 1, 0, 4, 0, 1, 0, 3,
        3, 0, 2, 4, 4,

In [4]:
y

array([1, 2, 3, 4, 5, 6])

In [27]:
#나이브 베이즈 모델을 만들고 위의 데이터를 훈련데이터로 삼아서 훈련하여 봅시다.  

In [28]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [29]:
#4번째 데이터의 class를 예측하여 봅시다. 

In [33]:
print(clf.predict(X[3].reshape(1,100))) 

[4]


In [34]:
#전체 훈련데이터를 예측하여 봅시다. 

In [37]:
clf.predict(X) 

array([1, 2, 3, 4, 5, 6])